runtime! debian.vim

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

if has("syntax")
  syntax on
endif

set background=dark
set history=1000
set suffixesadd+=.py,.go

set hidden
set list
set number

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noautoindent

set ignorecase
set smartcase
set incsearch
set hlsearch

set nosol
set noai
set mouse-=a
set laststatus=2

set foldmethod=indent
set foldlevel=99

nmap <silent> gq :nohlsearch<CR>
nmap <silent> gl :set list! number!<CR>
nmap <silent> gp :set paste!<CR>
nmap <silent> gn :NERDTreeToggle<CR>
nmap <silent> gw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><C-o>:noh<CR>

map <F12> :GoDebugStop<CR>
"map <F11> :GoDebugStep<CR>
"map <F10> :GoDebugNext<CR>
"map <F9> :GoDebugBreakpoint<CR>
"map <F8> :GoDebugHalt<CR>
map <F6> :GoDebugStart<CR>
"map <F5> :GoDebugContinue<CR>

cmap w!! w !sudo tee % > /dev/null

nmap <C-n> :bn<CR>
nmap <C-p> :bp<CR>
nmap <C-x> :bd<CR>

nnoremap j gj
nnoremap k gk
"nnoremap <TAB> zj
nnoremap <S-TAB> zk
nnoremap <silent> <Space> @=(foldlevel('.')?'zA':"\<Space>")<CR>

let g:skip_defaults_vim = 1
let python_highlight_all = 1

command! Q q
command! W w

"vmap X /y<C-R>"<CR>

set rtp+=/home/damyan/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
Plugin 'Yggdroot/indentLine'
Plugin 'preservim/nerdtree'
call vundle#end()

filetype on
filetype plugin on
filetype plugin indent on
let g:indentLine_enabled = 1
let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1
:set listchars+=tab:\ \ 
